# Generated by Django 3.2.7 on 2021-09-13 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basetable',
            fields=[
                ('base_id', models.AutoField(primary_key=True, serialize=False)),
                ('productname', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'basetable',
            },
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('original_price', models.IntegerField()),
                ('price', models.IntegerField()),
                ('base_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.basetable')),
            ],
            options={
                'db_table': 'properties',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('is_listimage', models.BooleanField(default=True)),
                ('url', models.URLField()),
                ('base_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.basetable')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.properties')),
            ],
            options={
                'db_table': 'images',
            },
        ),
        migrations.CreateModel(
            name='Dimensions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('length', models.DecimalField(decimal_places=2, max_digits=7)),
                ('width', models.DecimalField(decimal_places=2, max_digits=7)),
                ('heigth', models.DecimalField(decimal_places=2, max_digits=7)),
                ('base_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.basetable')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.properties')),
            ],
            options={
                'db_table': 'dimensions',
            },
        ),
    ]
